# This is a TOML config file.

###############################################################################
###                           Client Configuration                           ###
###############################################################################

# The network chain ID
chain-id = "localxion-1"

# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
keyring-backend = "test"

# CLI output format (text|json)
output = "text"

# <host>:<port> to CometBFT RPC interface for this chain
# (In your juno_hub_custom.json, you mapped 26657 -> 26157 for Xion, so point the CLI to 127.0.0.1:26157)
node = "tcp://127.0.0.1:26157"

# Transaction broadcasting mode (sync|async|block)
broadcast-mode = "sync"


###############################################################################
###                       Xion Tx Configuration                              ###
###############################################################################

# Amount of gas per transaction
gas = "auto"

# Price per unit of gas (ex: 0.005uxion)
gas-prices = "0.01uxion"

# Multiply estimated gas by this factor
gas-adjustment = "2"

# If you prefer to hard-code fees instead of auto gas prices:
fees = ""

fee-granter = ""
fee-payer = ""

# Optional memo to include in your Transactions
note = ""
