# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Base Configuration                            ###
###############################################################################

# The minimum gas prices a validator is willing to accept for processing
# a transaction. This can be 0 or near-zero in dev for frictionless testing.
minimum-gas-prices = "0uxion"

# How many states to prune. "default" = keep ~362,880 blocks,
# "everything" = keep only 2 blocks, "nothing" = full archive,
# or "custom" for your own pruning strategy. For local dev, "default" is fine.
pruning = "default"

pruning-keep-recent = "0"
pruning-interval = "0"

# If you want your chain to stop at a certain block/time for testing, set below:
halt-height = 0
halt-time = 0

# 0 means not pruning older blocks from Tendermint beyond the unbonding window.
min-retain-blocks = 0

# Speeds up repeated queries by caching interim states. Usually "true".
inter-block-cache = true

# Which events get indexed for transaction/event queries. Usually empty array for dev.
index-events = []

# iavl-cache-size is the number of IAVL nodes to keep in memory for performance.
iavl-cache-size = 781250

# Whether to enable fast node indexing in IAVL. Typically "false".
iavl-disable-fastnode = false

# Database backend for the application and snapshots. Usually an empty string for fallback.
app-db-backend = ""

###############################################################################
###                         Telemetry Configuration                         ###
###############################################################################

[telemetry]
enabled = false
enable-hostname = false
enable-hostname-label = false
enable-service-label = false
prometheus-retention-time = 0
global-labels = []
service-name = ""

###############################################################################
###                           API Configuration                             ###
###############################################################################

[api]
enable = false
swagger = false
address = "tcp://localhost:1317"
max-open-connections = 1000
rpc-read-timeout = 10
rpc-write-timeout = 0
rpc-max-body-bytes = 1000000
enabled-unsafe-cors = false

###############################################################################
###                           gRPC Configuration                            ###
###############################################################################

[grpc]
enable = true
address = "localhost:9090"
max-recv-msg-size = "10485760"
max-send-msg-size = "2147483647"

###############################################################################
###                        gRPC Web Configuration                           ###
###############################################################################

[grpc-web]
enable = true

###############################################################################
###                        State Sync Configuration                         ###
###############################################################################

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 2

###############################################################################
###                              State Streaming                            ###
###############################################################################

[streaming]
[streaming.abci]
keys = []
plugin = ""
stop-node-on-err = true

###############################################################################
###                         Mempool                                         ###
###############################################################################

[mempool]
# Negative 1 (-1) disables adding transactions to the mempool, 
# which is usually not what you want unless debugging. 
# Typically set to a positive number or 0 for "no limit".
max-txs = 5000

###############################################################################
###                         Wasm Configuration                              ###
###############################################################################

[wasm]
query_gas_limit = 3000000
memory_cache_size = 100
# simulation_gas_limit =

